[package]
name = "ecies_25519"
version = "0.1.0"
edition = "2021"
authors = ["Norm O <normo.pub@gmail.com>"]
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "0.8.0" }
base64 = "^0.13"
curve25519-parser = { version = "^0.2"}
curve25519-dalek = "3.1.0"
x25519-dalek = "^1.2"
digest = { version = "0.9.0" }
hex = "0.4.3"
hkdf = { version = "0.10.0" }
rand = "^0.8"
rand_core = "^0.5"
serde = { version = "1.0.125" }
sha2 = { version = "0.9.3" }
thiserror = "1.0.24"
zeroize = "1.3.0"

[dev-dependencies]
serde_json = "1.0.64"
serde_cbor = "0.11.1"